#! /bin/sh

### BEGIN INIT INFO
# Provides:          aesdsocket
# Required-Start:    $local_fs $network
# Required-Stop:     $local_fs $network
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start myservice at boot time
# Description:       Enable service myservice.
### END INIT INFO

DAEMON=/usr/bin/aesdsocket
DAEMON_ARGS=" -d "
NAME=$(basename $DAEMON)
DAEMON_DIR=$(dirname $DAEMON)
PIDFILE="/var/run/${NAME}.pid"
DAEMON_PID=
RETRY=5

get_pid () {
    if [ -f $PIDFILE ];
    then
        DAEMON_PID=$(/bin/cat $PIDFILE) 
    fi
}

check_daemon_status () {

    get_pid

    /usr/bin/kill -0 $DAEMON_PID 2> /dev/null

    if [ $? -eq 0 ];
    then
        echo "The $NAME is active now."
    else
        echo "The $NAME is inactive now."
    fi
}

case "$1" in
  start)
    echo "Starting ${NAME}"
    /sbin/start-stop-daemon -S --make-pidfile --name $NAME --pidfile /var/run/${NAME}.pid --oknodo --exec ${DAEMON} -- $DAEMON_ARGS
    # Command to start the service
    ;;
  stop)
    echo "Stopping ${NAME}"
    # Command to stop the service
    #/sbin/start-stop-daemon -K --remove-pidfile --pidfile /var/run/${NAME}.pid --name $NAME --retry $RETRY
    /sbin/start-stop-daemon -K --remove-pidfile --pidfile /var/run/${NAME}.pid --name $NAME --retry $RETRY
    ;;
  restart)
    echo "Restarting ${NAME}"
    ${DAEMON_DIR}/$NAME stop
    sleep 1 
    ${DAEMON_DIR}/$NAME start
    ;;
  status)
    #echo "Checking status of ${NAME}"
    check_daemon_status
    ;;
  *)
    echo "Usage: /etc/init.d/${NAME} {start|stop|restart|status}"
    exit 1
    ;;
esac

exit $? 
